"""add sales categories and recipient fields

Seeds the 5 fixed sales categories (Corporate/Metro/Upcountry/
Shop-Kikuubo/Factory Sales) as structural reference data — same precedent
as the Phase 2 migration that seeded the product list. Recipient DATA
(the initial Dakar/Derrick/Ayub/Fenecansi/Shop assignments and the
104-name Corporate Sales import) is deliberately NOT part of this
migration — that's business data requiring a preview and human approval,
done through the admin-triggered import tool instead
(webapp/services/recipient_import_service.py), never silently here.

Revision ID: 012e556ab7ad
Revises: b10744abb49e
Create Date: 2026-07-28 21:31:47.951809

"""
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012e556ab7ad'
down_revision = 'b10744abb49e'
branch_labels = None
depends_on = None

SALES_CATEGORIES = [
    "Corporate Sales",
    "Metro Sales",
    "Upcountry Sales",
    "Shop/Kikuubo Sales",
    "Factory Sales",
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_categories_name'), ['name'], unique=True)

    sales_categories_table = sa.table(
        'sales_categories',
        sa.column('name', sa.String),
        sa.column('active', sa.Boolean),
        sa.column('display_order', sa.Integer),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    op.bulk_insert(sales_categories_table, [
        {"name": name, "active": True, "display_order": i, "created_at": now, "updated_at": now}
        for i, name in enumerate(SALES_CATEGORIES, start=1)
    ])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_category_id', sa.Integer(), nullable=True))
        # server_default is required here: this ALTER runs against a
        # customers table that may already have rows (real production
        # data), and SQLite's batch-table-recreate strategy needs a value
        # to backfill NOT NULL columns with — the model's Python-side
        # default=False only applies to rows inserted after this point.
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('merged_into_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_is_temporary'), ['is_temporary'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_merged_into_id'), ['merged_into_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_sales_category_id'), ['sales_category_id'], unique=False)
        batch_op.create_foreign_key('fk_customers_merged_into_id_customers', 'customers', ['merged_into_id'], ['id'])
        batch_op.create_foreign_key('fk_customers_sales_category_id_sales_categories', 'sales_categories', ['sales_category_id'], ['id'])

    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_category_name_snapshot', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('customer_name_snapshot', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_dispatches_sales_category_id'), ['sales_category_id'], unique=False)
        batch_op.create_foreign_key('fk_dispatches_sales_category_id_sales_categories', 'sales_categories', ['sales_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dispatches_sales_category_id_sales_categories', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dispatches_sales_category_id'))
        batch_op.drop_column('customer_name_snapshot')
        batch_op.drop_column('sales_category_name_snapshot')
        batch_op.drop_column('sales_category_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_merged_into_id_customers', type_='foreignkey')
        batch_op.drop_constraint('fk_customers_sales_category_id_sales_categories', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_sales_category_id'))
        batch_op.drop_index(batch_op.f('ix_customers_merged_into_id'))
        batch_op.drop_index(batch_op.f('ix_customers_is_temporary'))
        batch_op.drop_column('merged_into_id')
        batch_op.drop_column('is_temporary')
        batch_op.drop_column('sales_category_id')

    with op.batch_alter_table('sales_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_categories_name'))

    op.drop_table('sales_categories')
    # ### end Alembic commands ###
