"""add dispatches and dispatch_lines

Revision ID: 64984c2b0aba
Revises: a939d0b27a3e
Create Date: 2026-07-28 19:35:46.507256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64984c2b0aba'
down_revision = 'a939d0b27a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_number', sa.String(length=40), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_override', sa.Boolean(), nullable=False),
    sa.Column('duplicate_override_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_by', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatches_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_dispatch_number'), ['dispatch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_status'), ['status'], unique=False)

    op.create_table('dispatch_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cartons', sa.Integer(), nullable=False),
    sa.Column('packs', sa.Integer(), nullable=False),
    sa.Column('pieces', sa.Integer(), nullable=False),
    sa.Column('base_unit_qty', sa.Integer(), nullable=False),
    sa.Column('packaging_rule_id', sa.Integer(), nullable=False),
    sa.Column('line_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['packaging_rule_id'], ['packaging_rules.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_lines_dispatch_id'), ['dispatch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_lines_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_lines_dispatch_id'))

    op.drop_table('dispatch_lines')
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatches_status'))
        batch_op.drop_index(batch_op.f('ix_dispatches_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_dispatches_dispatch_number'))
        batch_op.drop_index(batch_op.f('ix_dispatches_date'))
        batch_op.drop_index(batch_op.f('ix_dispatches_customer_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_created_by'))

    op.drop_table('dispatches')
    # ### end Alembic commands ###
