"""add low_stock_threshold to products

Revision ID: b10744abb49e
Revises: b4961f69011b
Create Date: 2026-07-28 20:25:57.768358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10744abb49e'
down_revision = 'b4961f69011b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('low_stock_threshold')

    # ### end Alembic commands ###
