"""add daily_figures, stock_adjustments, legacy_migration_flags

Revision ID: b4961f69011b
Revises: 64984c2b0aba
Create Date: 2026-07-28 19:59:26.299333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4961f69011b'
down_revision = '64984c2b0aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_migration_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entries_row_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('field', sa.String(length=20), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legacy_migration_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legacy_migration_flags_entries_row_id'), ['entries_row_id'], unique=False)

    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('delta_base_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_adjustments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_adjustments_product_id'), ['product_id'], unique=False)

    op.create_table('daily_figures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('shift', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('opening_cartons', sa.Integer(), nullable=False),
    sa.Column('opening_packs', sa.Integer(), nullable=False),
    sa.Column('opening_pieces', sa.Integer(), nullable=False),
    sa.Column('opening_base_qty', sa.Integer(), nullable=False),
    sa.Column('return_cartons', sa.Integer(), nullable=False),
    sa.Column('return_packs', sa.Integer(), nullable=False),
    sa.Column('return_pieces', sa.Integer(), nullable=False),
    sa.Column('return_base_qty', sa.Integer(), nullable=False),
    sa.Column('production_cartons', sa.Integer(), nullable=False),
    sa.Column('production_packs', sa.Integer(), nullable=False),
    sa.Column('production_pieces', sa.Integer(), nullable=False),
    sa.Column('production_base_qty', sa.Integer(), nullable=False),
    sa.Column('packaging_rule_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['packaging_rule_id'], ['packaging_rules.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'shift', 'product_id', name='uq_daily_figure_date_shift_product')
    )
    with op.batch_alter_table('daily_figures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_figures_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_figures_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_figures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_figures_product_id'))
        batch_op.drop_index(batch_op.f('ix_daily_figures_date'))

    op.drop_table('daily_figures')
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_date'))

    op.drop_table('stock_adjustments')
    with op.batch_alter_table('legacy_migration_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legacy_migration_flags_entries_row_id'))

    op.drop_table('legacy_migration_flags')
    # ### end Alembic commands ###
